// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file was generated by the app_sizer PreScale Generator.

import 'package:app_sizer/app_sizer.dart';

/// Automated setup: pass this as 'precalcFunction' parameter to AppSizer.
void useTestAppSizerPrecalc(AppSizesNotifier notifier) {
  final manager = PreScaleManager();

  // Pre-calc w
  manager.precalcList(notifier, [
    1.0,
    100.0,
  ], type: 'w');

  // Pre-calc h
  manager.precalcList(notifier, [
    20.0,
    50.0,
    50.5,
  ], type: 'h');

  // Pre-calc sp
  manager.precalcList(notifier, [
    16.0,
  ], type: 'sp');

  // Pre-calc r
  manager.precalcList(notifier, [
    12.0,
  ], type: 'r');

}
