name: app_sizer
description: A high-performance responsive framework for Flutter that makes your UI adapt seamlessly to any screen size with intuitive extensions and smart caching.
version: 0.0.3
repository: https://github.com/Moo-Meshrif/app_sizer
homepage: https://github.com/Moo-Meshrif/app_sizer
issue_tracker: https://github.com/Moo-Meshrif/app_sizer/issues
platforms:
  android:
  ios:
  web:
  macos:
  linux:
  windows:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

executables:
  generate_prescale: generate_prescale

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
