// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file was generated by the app_sizer PreScale Generator.

import 'package:app_sizer/app_sizer.dart';

/// Automated setup: pass this as 'precalcFunction' parameter to AppSizer.
void useAppSizerPrecalc(AppSizesNotifier notifier) {
  final manager = PreScaleManager();

  // Pre-calc w
  manager.precalcList(notifier, [
    10.0,
    16.0,
    20.0,
    160.0,
  ], type: ScaleType.w);

  // Pre-calc h
  manager.precalcList(notifier, [
    4.0,
    10.0,
    16.0,
    20.0,
    30.0,
    40.0,
    80.0,
    200.0,
  ], type: ScaleType.h);

  // Pre-calc sp
  manager.precalcList(notifier, [
    10.0,
    12.0,
    16.0,
  ], type: ScaleType.sp);

  // Pre-calc r
  manager.precalcList(notifier, [
    4.0,
    8.0,
    12.0,
    16.0,
    20.0,
  ], type: ScaleType.r);

}
