// ignore_for_file: avoid_print

import 'dart:io';

void main(List<String> args) {
  Logger.info('🚀 Starting PreScale Generator...');

  final scanPaths = <String>[];
  String? outputPath;
  String functionName = 'useAppSizerPrecalc';

  // Simple argument parsing
  for (int i = 0; i < args.length; i++) {
    final arg = args[i];
    if (arg == '--output' || arg == '-o') {
      if (i + 1 < args.length) {
        outputPath = args[++i];
      }
    } else if (arg == '--name' || arg == '-n') {
      if (i + 1 < args.length) {
        functionName = args[++i];
      }
    } else if (!arg.startsWith('-')) {
      scanPaths.add(arg);
    }
  }

  // If NO arguments provided, run in "Smart Multi-Target Mode"
  if (scanPaths.isEmpty && outputPath == null && args.isEmpty) {
    _runMultiTargetGeneration();
    return;
  }

  // Otherwise, run single target (legacy / manual mode)
  if (scanPaths.isEmpty) {
    if (Directory('lib').existsSync()) scanPaths.add('lib');
  }

  outputPath ??= 'lib/app_sizer_precalc.g.dart';
  _generateFor(scanPaths, outputPath, functionName);
}

void _runMultiTargetGeneration() {
  Logger.info('🧐 Running Smart Multi-Target Mode...');

  // 1. Example App & Test Suite
  if (Directory('example').existsSync()) {
    _generateFor(
      ['example'],
      'example/lib/app_sizer_precalc.g.dart',
      'useAppSizerPrecalc',
    );

    // 2. Test Suite
    if (Directory('test').existsSync()) {
      _generateFor(
        ['test'],
        'test/test_app_sizer_precalc.g.dart',
        'useTestAppSizerPrecalc',
        silent: true,
      );
    }
  } else {
    // 3. Generic App
    _generateFor(
      ['lib'],
      'lib/app_sizer_precalc.g.dart',
      'useAppSizerPrecalc',
    );
  }

  Logger.success('✨ All targets generated successfully!');
}

void _generateFor(
    List<String> scanPaths, String outputPath, String functionName,
    {bool silent = false}) {
  if (!silent)
    Logger.info('📂 Scanning ${scanPaths.join(', ')} -> $outputPath');

  final wNumbers = <double>{};
  final hNumbers = <double>{};
  final textNumbers = <double>{};
  final radiusNumbers = <double>{};

  final regex = RegExp(r'(\d+(?:\.\d+)?)\.(w|h|vGap|hGap|sp|r)');

  final appSizerFiles = <String>{};
  for (final path in scanPaths) {
    final dir = Directory(path);
    if (!dir.existsSync()) continue;

    final files = dir
        .listSync(recursive: true)
        .whereType<File>()
        .where((f) => f.path.endsWith('.dart'));

    for (final file in files) {
      if (file.path.endsWith('.g.dart')) continue;

      final content = file.readAsStringSync();

      // Check if this file contains AppSizer instances to inject into later
      if (content.contains('AppSizer(')) {
        appSizerFiles.add(file.path);
      }

      final matches = regex.allMatches(content);
      for (final match in matches) {
        final number = double.tryParse(match.group(1) ?? '');
        final type = match.group(2);
        if (number != null) {
          switch (type) {
            case 'w':
            case 'hGap':
              wNumbers.add(number);
              break;
            case 'h':
            case 'vGap':
              hNumbers.add(number);
              break;
            case 'sp':
              textNumbers.add(number);
              break;
            case 'r':
              radiusNumbers.add(number);
              break;
          }
        }
      }
    }
  }

  final buffer = StringBuffer();
  buffer.writeln("// AUTO-GENERATED FILE. DO NOT MODIFY.");
  buffer.writeln(
      "// This file was generated by the app_sizer PreScale Generator.");
  buffer.writeln("");
  buffer.writeln("import 'package:app_sizer/app_sizer.dart';\n");

  buffer.writeln(
      "/// Automated setup: pass this as 'precalcFunction' parameter to AppSizer.");
  buffer.writeln("void $functionName(AppSizesNotifier notifier) {");
  buffer.writeln("  final manager = PreScaleManager();\n");

  void writeList(Set<double> numbers, String type) {
    if (numbers.isEmpty) return;
    final sorted = numbers.toList()..sort();
    buffer.writeln("  // Pre-calc $type");
    buffer.writeln("  manager.precalcList(notifier, [");
    for (final num in sorted) {
      buffer.writeln("    $num,");
    }
    buffer.writeln("  ], type: '$type');\n");
  }

  writeList(wNumbers, 'w');
  writeList(hNumbers, 'h');
  writeList(textNumbers, 'sp');
  writeList(radiusNumbers, 'r');
  buffer.writeln("}");

  final outputFile = File(outputPath);
  if (!outputFile.parent.existsSync()) {
    outputFile.parent.createSync(recursive: true);
  }
  outputFile.writeAsStringSync(buffer.toString());

  _injectSetup(outputPath, functionName, appSizerFiles, silent: silent);
}

void _injectSetup(
    String outputPath, String functionName, Set<String> appSizerFiles,
    {bool silent = false}) {
  if (appSizerFiles.isNotEmpty) {
    for (final path in appSizerFiles) {
      _injectIntoFile(File(path), outputPath, functionName, silent: silent);
    }
    return;
  }

  // Fallback to searching main.dart if no AppSizer was found in scanned paths
  File? mainFile;

  if (outputPath.contains('/test/') || outputPath.startsWith('test/')) {
    final testPaths = ['test/responsive_test.dart', 'test/widget_test.dart'];
    for (final path in testPaths) {
      if (File(path).existsSync()) {
        _injectIntoFile(File(path), outputPath, functionName, silent: silent);
      }
    }
    return;
  }

  if (outputPath.startsWith('example/')) {
    mainFile = File('example/lib/main.dart');
  } else if (outputPath.startsWith('lib/')) {
    mainFile = File('lib/main.dart');
  }

  if (mainFile != null && mainFile.existsSync()) {
    _injectIntoFile(mainFile, outputPath, functionName, silent: silent);
  }
}

void _injectIntoFile(File file, String outputPath, String functionName,
    {bool silent = false}) {
  String content = file.readAsStringSync();
  if (!content.contains('AppSizer(')) return;

  bool modified = false;

  String importLine = "import '${_getRelativePath(file.path, outputPath)}';";

  if (!content.contains(importLine)) {
    final lastImportMatch =
        RegExp(r'^import .*;', multiLine: true).allMatches(content).lastOrNull;
    if (lastImportMatch != null) {
      content = content.replaceRange(
          lastImportMatch.end, lastImportMatch.end, "\n$importLine");
    } else {
      content = "$importLine\n$content";
    }
    modified = true;
  }

  // 1. Remove old-style global setup call if it exists
  final oldCallRegex = RegExp('$functionName\\(\\);?\\n?\\s*');
  if (content.contains(oldCallRegex)) {
    content = content.replaceAll(oldCallRegex, '');
    modified = true;
  }

  // 2. Inject into AppSizer instances
  if (!content.contains('precalcFunction: $functionName')) {
    content = content.replaceAll(
        'AppSizer(', 'AppSizer(\n      precalcFunction: $functionName,');
    modified = true;
  }

  if (modified) {
    file.writeAsStringSync(content);
    // Format the file
    Process.runSync('dart', ['format', file.path]);
  }
}

String _getRelativePath(String from, String to) {
  final fromParts = from.split(RegExp(r'[/\\]'));
  final toParts = to.split(RegExp(r'[/\\]'));

  int commonIndex = 0;
  while (commonIndex < fromParts.length - 1 &&
      commonIndex < toParts.length - 1 &&
      fromParts[commonIndex] == toParts[commonIndex]) {
    commonIndex++;
  }

  final buffer = StringBuffer();
  for (int i = commonIndex; i < fromParts.length - 1; i++) {
    buffer.write('../');
  }

  for (int i = commonIndex; i < toParts.length; i++) {
    buffer.write(toParts[i]);
    if (i < toParts.length - 1) buffer.write('/');
  }

  return buffer.toString();
}

class Logger {
  static const String _reset = '\x1B[0m',
      _green = '\x1B[32m',
      _cyan = '\x1B[36m';
  static void info(String m) => print('$_cyan$m$_reset');
  static void success(String m) => print('$_green$m$_reset');
  static void error(String m) => print('\x1B[31m$m$_reset');
}
